# Generated by Django 5.2.1 on 2025-06-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSummaryForPostgres',
            fields=[
                ('game_id', models.CharField(primary_key=True, serialize=False)),
                ('home_team', models.CharField()),
                ('home_score', models.IntegerField()),
                ('away_team', models.CharField()),
                ('away_score', models.IntegerField()),
                ('game_sequence', models.IntegerField()),
                ('status_id', models.IntegerField()),
                ('status_text', models.CharField()),
                ('live_period', models.IntegerField()),
                ('live_clock', models.CharField()),
                ('game_date_jst', models.DateField()),
            ],
            options={
                'db_table': 'game_summaries',
            },
        ),
        migrations.CreateModel(
            name='SeasonRangeForPostgres',
            fields=[
                ('season', models.CharField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('update_game_summaries_date', models.DateField()),
            ],
            options={
                'db_table': 'season_ranges',
            },
        ),
    ]
