# Generated by Django 5.2.1 on 2025-06-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data_collecter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxScoreDataForPostgres',
            fields=[
                ('game_id', models.CharField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'box_score_data',
            },
        ),
    ]
