# Generated by Django 5.2.1 on 2025-07-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data_collecter', '0002_boxscoredataforpostgres'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxScoreSummaryForPostgres',
            fields=[
                ('game_id', models.CharField(primary_key=True, serialize=False)),
                ('game_date_jst', models.DateField()),
                ('home', models.JSONField()),
                ('away', models.JSONField()),
            ],
            options={
                'db_table': 'box_score_summary',
            },
        ),
    ]
