# Generated by Django 5.2.1 on 2025-07-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamOnGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField()),
                ('team_id', models.IntegerField()),
                ('abbreviation', models.CharField()),
                ('logo', models.CharField()),
                ('score', models.IntegerField()),
                ('is_home', models.BooleanField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_id', 'is_home'), name='unique_game_id_is_home'), models.UniqueConstraint(fields=('game_id', 'team_id'), name='unique_game_id_team_id')],
            },
        ),
        migrations.CreateModel(
            name='GameSummary',
            fields=[
                ('game_id', models.CharField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('status_id', models.IntegerField()),
                ('status_text', models.CharField()),
                ('live_period', models.IntegerField()),
                ('live_clock', models.CharField()),
                ('game_date_est', models.DateField()),
                ('away_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_on_game', to='rest_api.teamongame')),
                ('home_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_on_game', to='rest_api.teamongame')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerOnGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('name', models.CharField()),
                ('jersey', models.CharField(blank=True, null=True)),
                ('position', models.CharField(blank=True, null=True)),
                ('is_starter', models.BooleanField()),
                ('is_inactive', models.BooleanField()),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('team_on_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.teamongame')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team_on_game', 'player_id'), name='unique_team_on_game_player_id')],
            },
        ),
    ]
