# Generated by Django 5.2.1 on 2025-07-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField()),
                ('logo', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='GameSummary',
            fields=[
                ('game_id', models.CharField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('status_id', models.IntegerField()),
                ('status_text', models.CharField()),
                ('live_period', models.IntegerField()),
                ('live_clock', models.CharField()),
                ('game_date_est', models.DateField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='rest_api.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='rest_api.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerOnGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home', models.BooleanField()),
                ('player_id', models.IntegerField()),
                ('name', models.CharField()),
                ('jersey', models.CharField(blank=True, null=True)),
                ('position', models.CharField(blank=True, null=True)),
                ('is_starter', models.BooleanField()),
                ('is_inactive', models.BooleanField()),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rest_api.gamesummary')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_id', 'player_id'), name='unique_game_id_player_id')],
            },
        ),
    ]
