# Generated by Django 5.2.1 on 2025-10-04 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0002_seasonsummary_regularseasonteamstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxscore",
            name="game_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="rest_api.gamesummary",
            ),
        ),
    ]
